### ISSUE TITLE
Missing function call

### ISSUE THREAD

**Issue by ElectricalVeins** [Dr-Khalilov/mini_game#1]
In the following lines function calls are missing. Call the startGame function in onClick handler, or simply pass startGame function as event handler

https://github.com/Dr-Khalilov/mini_game/blob/e731306834955404f8ec2a3e8945300b71a4cadf/src/components/Game.tsx#L90
https://github.com/Dr-Khalilov/mini_game/blob/e731306834955404f8ec2a3e8945300b71a4cadf/src/components/Game.tsx#L92
https://github.com/Dr-Khalilov/mini_game/blob/e731306834955404f8ec2a3e8945300b71a4cadf/src/components/Game.tsx#L94
https://github.com/Dr-Khalilov/mini_game/blob/e731306834955404f8ec2a3e8945300b71a4cadf/src/components/Game.tsx#L96

**Comment by umar-khalilov** [comment]
Fixed error
